swagger: '2.0'
info:
  title: Bank Argent API documentation
  description: Contains the API endpoints for the transactions page available in this codebase
  version: '1.0.0'
  termsOfService: 'http://swagger.io/terms/'
host: localhost:3001
basePath: /api/v1
schemes:
  - http
paths:
  /transactions:
    get:
      security:
        - Bearer: []
      tags:
        - User Module
      summary: Transactions
      description: The API call to this route will allow the user to view all their transactions for the current month, grouped by account.
      parameters:
        - in: body
          name: body
          description: category Payload
          required: true
          schema:
            $ref: '#/definitions/transactions'
      produces:
        - application/json
      responses:
        '200':
          description: The category has just been successfully created
          schema:
            $ref: '#/definitions/transactionsResponse'
        '400':
          description: Invalid Fields
        '401':
          description: Valid authentication information is missing for the targeted resource
        '404':
          description: The server route is wrong
        '500':
          description: Internal Server Error
  /transactions/details:
     get:
      security:
        - Bearer: []
      tags:
        - User Module
      summary: Details
      description: API call to this route will show transaction details.
      parameters:
        - in: header
          name: Authorization
          description: Attach userID
          required: true
          type: string
      produces:
        - application/json
      responses:
        '200':
          description: The category has just been successfully created
          schema:
            $ref: '#/definitions/detailsResponse'
        '400':
          description: Invalid Fields
        '401':
          description: Valid authentication information is missing for the targeted resource
        '404':
          description: The server route is wrong
        '500':
          description: Internal Server Error
  /transactions/details/category:
    patch:
      security:
        - Bearer: []
      tags:
        - User Module
      summary: Update Category
      description: Will allow updating of the dropdown
      parameters:
        - in: header
          name: Authorization
          description: Attach userID
          required: true
          type: string
        - in: body
          name: body
          description: category Payload
          required: true
          schema:
            $ref: '#/definitions/category'
      produces:
        - application/json
      responses:
        '200':
          description: Category has just been successfully updated
          schema:
            $ref: '#/definitions/categoryResponse'
        '400':
          description: Invalid Fields
        '401':
          description: Valid authentication information is missing for the targeted resource
        '404':
          description: The server route is wrong
        '500':
          description: Internal Server Error
    delete:
      security:
        - Bearer: []
      tags:
        - User Module
      summary: Delete Category
      description: Deletes the category registered by the user
      parameters:
        - in: header
          name: Authorization
          description: Attach userID
          required: true
          type: string
        - in: body
          name: body
          description: Note Payload
          required: true
          schema:
            $ref: '#/definitions/category'
      produces:
        - application/json
      responses:
        '200':
          description: Deletion successful
          schema:
            $ref: '#/definitions/categoryDeleteResponse'
        '400':
          description: Invalid Fields
        '401':
          description: Valid authentication information is missing for the targeted resource
        '404':
          description: The server route is wrong
        '500':
          description: Internal Server Error
  /transactions/details/note:
    patch:
      security:
        - Bearer: []
      tags:
        - User Module
      summary: Update Note
      description: Update of the rating registered by the user
      parameters:
        - in: header
          name: Authorization
          description: Attach userID
          required: true
          type: string
        - in: body
          name: body
          description: Note Payload
          required: true
          schema:
            $ref: '#/definitions/note'
      produces:
        - application/json
      responses:
        '200':
          description: Note has just been successfully updated
          schema:
            $ref: '#/definitions/noteResponse'
        '400':
          description: Invalid Fields
        '401':
          description: Valid authentication information is missing for the targeted resource
        '404':
          description: The server route is wrong
        '500':
          description: Internal Server Error
    delete:
      security:
        - Bearer: []
      tags:
        - User Module
      summary: Delete Note
      description: deletes the note entered by the user
      parameters:
        - in: body
          name: body
          description: Note Payload
          required: true
          schema:
            $ref: '#/definitions/note'
      produces:
        - application/json
      responses:
        '200':
          description: Deletion successful
          schema:
            $ref: '#/definitions/noteDeleteResponse'
        '400':
          description: Invalid Fields
        '401':
          description: Valid authentication information is missing for the targeted resource
        '404':
          description: The server route is wrong
        '500':
          description: Internal Server Error
          
securityDefinitions:
  Bearer:
    type: apiKey
    name: Authorization
    in: header
definitions:
  transactions:
    properties:
      userID:
        type: string
        description: user category
  category:
    properties:
      category:
        type: string
        description: user category
  note:
    properties:
      note:
        type: string
        description: user category
  transactionsResponse:
    type: object
    properties:
      date:
        type: string
      description:
        type: string
      amount:
        type: integer
      balance:
        type: integer
  detailsResponse:
    type: object
    properties:
      transaction type:
        type: string
      category:
        type: string
      note:
        type: string
  categoryResponse:
    type: object
    properties:
      id:
        type: string
      category:
        type: string
  categoryDeleteResponse:
    type: object
    properties:
      category:
        type: object
  noteResponse:
    type: object
    properties:
      id:
        type: string
      note:
        type: string
  noteDeleteResponse:
    type: object
    properties:
      note:
        type: object